// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-scans.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.112.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-scans.ts
var list_scans_default = defineTool({
  name: "list_scans",
  title: "List hemoglobin scans",
  description: "List the signed-in user's recent HemaLen hemoglobin screening results, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("How many scans to return (1-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("scans").select("id, hb_value, severity, mode, notes, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { scans: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-latest-scan.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_latest_scan_default = defineTool2({
  name: "get_latest_scan",
  title: "Get latest scan",
  description: "Get the signed-in user's most recent hemoglobin screening result, if any.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("scans").select("id, hb_value, severity, mode, notes, created_at").order("created_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No scans recorded yet." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { scan: data }
    };
  }
});

// src/lib/mcp/tools/log-scan.ts
import { defineTool as defineTool3, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var severity = z2.enum(["normal", "mild", "moderate", "severe", "critical"]);
function severityFor(hb) {
  if (hb >= 12) return "normal";
  if (hb >= 11) return "mild";
  if (hb >= 9) return "moderate";
  if (hb >= 7) return "severe";
  return "critical";
}
var log_scan_default = defineTool3({
  name: "log_scan",
  title: "Log a hemoglobin reading",
  description: "Record a hemoglobin reading (g/dL) for the signed-in user, e.g. a lab result. Severity is derived automatically when not provided.",
  inputSchema: {
    hb_value: z2.number().min(1).max(25).describe("Hemoglobin value in g/dL."),
    mode: z2.enum(["eyelid", "nail", "lab"]).default("lab").describe("How the reading was obtained."),
    severity: severity.nullable().default(null).describe("Optional severity override."),
    notes: z2.string().max(500).nullable().default(null).describe("Optional free-text note.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ hb_value, mode, severity: level, notes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError("Could not resolve the signed-in user.");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("scans").insert({
      user_id: userId,
      hb_value,
      mode: mode ?? "lab",
      severity: level ?? severityFor(hb_value),
      notes: notes ?? null
    }).select("id, hb_value, severity, mode, notes, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { scan: data }
    };
  }
});

// src/lib/mcp/tools/anemia-guidance.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var guidance = {
  ranges: "Normal hemoglobin ranges (g/dL): men 13.5-17.5, women 12.0-15.5, children 11.0-16.0. HemaLen severity bands: normal >=12, mild 11-12, moderate 9-11, severe 7-9, critical <7. Screening only - not a diagnosis.",
  symptoms: "Common anemia symptoms: fatigue and weakness, pale skin (especially lower eyelids and nail beds), shortness of breath, dizziness, cold hands and feet, headaches, brittle nails.",
  diet: "Iron-rich foods: spinach, moringa, beetroot, broccoli, lentils, chickpeas, kidney beans, eggs, fish, lean red meat, pumpkin and sesame seeds, dates. Pair with vitamin C (orange, lemon, guava) to boost absorption, and avoid tea or coffee with meals.",
  emergency: "If hemoglobin is below 8 g/dL or symptoms are severe: stay calm, sit down if dizzy, contact a doctor immediately, and go to the nearest hospital. Emergency services in India: 108.",
  scanning: "How to scan in HemaLen AI: open the Scan screen, choose Eyelid Mode or Nail Bed Mode, start the camera, gently pull the lower eyelid down, align it inside the guide circle, hold still and capture. The AI estimate appears on the Results screen."
};
var anemia_guidance_default = defineTool4({
  name: "anemia_guidance",
  title: "Anemia guidance",
  description: "Look up HemaLen's reference guidance on hemoglobin ranges, anemia symptoms, iron-rich diet, emergency steps, or how to scan.",
  inputSchema: {
    topic: z3.enum(["ranges", "symptoms", "diet", "emergency", "scanning"]).describe("Which guidance topic to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ topic }) => ({ content: [{ type: "text", text: guidance[topic] }] })
});

// src/lib/mcp/index.ts
var projectRef = "mogavuqeqxxgzniuqlpy";
var mcp_default = defineMcp({
  name: "hema-health-ai",
  title: "Hema Health AI",
  version: "0.1.0",
  instructions: "Tools for HemaLen AI, a non-invasive anemia screening app. Use `list_scans` and `get_latest_scan` to read the signed-in user's hemoglobin screening history, `log_scan` to record a new hemoglobin reading, and `anemia_guidance` for reference information on ranges, symptoms, diet, emergencies, and scanning. Results are screening estimates, never a medical diagnosis.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_scans_default, get_latest_scan_default, log_scan_default, anemia_guidance_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
